package com.gdut.dongjun.domain.dao.system;

/**
 * 
 * @author Sherlock-lee
 * @state 单主键类的DAO接口
 * @param <T> T为单主键PO类
 */
public interface SinglePrimaryKeyBaseMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public T selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg_envelope
     *
     * @mbggenerated Sun Mar 22 05:28:40 CST 2015
     */
    public int updateByPrimaryKey(T record);
}