package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ControlMearsureHitchEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_hitch_event.id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_hitch_event.switch_id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    private String switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_hitch_event.hitch_reason
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    private Integer hitchReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_hitch_event.hitch_time
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    private Date hitchTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_hitch_event.id
     *
     * @return the value of control_mearsure_hitch_event.id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_hitch_event.id
     *
     * @param id the value for control_mearsure_hitch_event.id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_hitch_event.switch_id
     *
     * @return the value of control_mearsure_hitch_event.switch_id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_hitch_event.switch_id
     *
     * @param switchId the value for control_mearsure_hitch_event.switch_id
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_hitch_event.hitch_reason
     *
     * @return the value of control_mearsure_hitch_event.hitch_reason
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public Integer getHitchReason() {
        return hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_hitch_event.hitch_reason
     *
     * @param hitchReason the value for control_mearsure_hitch_event.hitch_reason
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public void setHitchReason(Integer hitchReason) {
        this.hitchReason = hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_hitch_event.hitch_time
     *
     * @return the value of control_mearsure_hitch_event.hitch_time
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public Date getHitchTime() {
        return hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_hitch_event.hitch_time
     *
     * @param hitchTime the value for control_mearsure_hitch_event.hitch_time
     *
     * @mbggenerated Fri Nov 20 20:20:15 CST 2015
     */
    public void setHitchTime(Date hitchTime) {
        this.hitchTime = hitchTime;
    }
}