package com.gdut.dongjun.domain.po;

import java.util.Date;

public class ControlMearsureCurrent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_current.id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_current.time
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_current.phase
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_current.value
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_current.switch_id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    private String switchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_current.id
     *
     * @return the value of control_mearsure_current.id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_current.id
     *
     * @param id the value for control_mearsure_current.id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_current.time
     *
     * @return the value of control_mearsure_current.time
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_current.time
     *
     * @param time the value for control_mearsure_current.time
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_current.phase
     *
     * @return the value of control_mearsure_current.phase
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_current.phase
     *
     * @param phase the value for control_mearsure_current.phase
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_current.value
     *
     * @return the value of control_mearsure_current.value
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_current.value
     *
     * @param value the value for control_mearsure_current.value
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_current.switch_id
     *
     * @return the value of control_mearsure_current.switch_id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_current.switch_id
     *
     * @param switchId the value for control_mearsure_current.switch_id
     *
     * @mbggenerated Sat Nov 14 14:24:15 CST 2015
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

	@Override
	public String toString() {
		return "ControlMearsureCurrent [id=" + id + ", time=" + time + ", phase=" + phase + ", value=" + value
				+ ", switchId=" + switchId + "]";
	}
    
}