package com.gdut.dongjun.domain.po;

public class ControlMearsureSwitch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.name
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.address
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.sim_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.device_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.longitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.latitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mearsure_switch.line_id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    private String lineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.id
     *
     * @return the value of control_mearsure_switch.id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.id
     *
     * @param id the value for control_mearsure_switch.id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.name
     *
     * @return the value of control_mearsure_switch.name
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.name
     *
     * @param name the value for control_mearsure_switch.name
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.address
     *
     * @return the value of control_mearsure_switch.address
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.address
     *
     * @param address the value for control_mearsure_switch.address
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.sim_number
     *
     * @return the value of control_mearsure_switch.sim_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.sim_number
     *
     * @param simNumber the value for control_mearsure_switch.sim_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.device_number
     *
     * @return the value of control_mearsure_switch.device_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.device_number
     *
     * @param deviceNumber the value for control_mearsure_switch.device_number
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.longitude
     *
     * @return the value of control_mearsure_switch.longitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.longitude
     *
     * @param longitude the value for control_mearsure_switch.longitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.latitude
     *
     * @return the value of control_mearsure_switch.latitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.latitude
     *
     * @param latitude the value for control_mearsure_switch.latitude
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mearsure_switch.line_id
     *
     * @return the value of control_mearsure_switch.line_id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mearsure_switch.line_id
     *
     * @param lineId the value for control_mearsure_switch.line_id
     *
     * @mbggenerated Mon Nov 23 12:04:38 CST 2015
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }
}