package com.gdut.dongjun.domain.po;

import java.util.HashMap;
import java.util.Map;

public class HighVoltageOperation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_operation.switch_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_operation.user_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_operation.operation_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String operationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_operation.id
     *
     * @return the value of high_voltage_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_operation.id
     *
     * @param id the value for high_voltage_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_operation.switch_id
     *
     * @return the value of high_voltage_operation.switch_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_operation.switch_id
     *
     * @param switchId the value for high_voltage_operation.switch_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_operation.user_id
     *
     * @return the value of high_voltage_operation.user_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_operation.user_id
     *
     * @param userId the value for high_voltage_operation.user_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_operation.operation_id
     *
     * @return the value of high_voltage_operation.operation_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_operation.operation_id
     *
     * @param operationId the value for high_voltage_operation.operation_id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }
    
    public Map<String, Object> getMap(String userId, String switchId, String operationId) {
    	Map<String, Object> result = new HashMap<>(4);
    	result.put("user_id", userId);
    	result.put("switch_id", switchId);
    	result.put("operation_id", operationId);
    	return result;
    }
    
    public Map<String, Object> getMap(String id, String userId, String switchId, String operationId) {
    	Map<String, Object> result = new HashMap<>(5);
    	result.put("id", id);
    	result.put("user_id", userId);
    	result.put("switch_id", switchId);
    	result.put("operation_id", operationId);
    	return result;
    }
    
    public static Map<String, Object> getMap(String userId, String switchId) {
    	Map<String, Object> result = new HashMap<>(4);
    	result.put("user_id", userId);
    	result.put("switch_id", switchId);
    	return result;
    }
    
    public static Map<String, Object> getAnoMap(String switchId, String type) {
    	Map<String, Object> result = new HashMap<>(4);
    	result.put("switch_id", switchId);
    	result.put("operation_id", type);
    	return result;
    } 
    
    public HighVoltageOperation(Map<String, Object> map) {
    	
    	if(map.get("user_id") != null) {
    		this.userId = (String)map.get("user_id");
    	}
    	if(map.get("switch_id") != null) {
    		this.switchId = (String)map.get("switch_id");
    	}
    	if(map.get("operation_id") != null) {
    		this.operationId = (String)map.get("operation_id");
    	}
    }
    
    public HighVoltageOperation(String id, String userId, String switchId, String operationId) {
    	this.id = id;
    	this.userId = userId;
    	this.switchId = switchId;
    	this.operationId = operationId;
    }
    
    public HighVoltageOperation() {
    	super();
    }
}