package com.gdut.dongjun.domain.po;

import java.util.Date;

public class HighVoltageHitchEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.switch_id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    private String switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    private Integer hitchReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_phase
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    private String hitchPhase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    private Date hitchTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_hitch_event.id
     *
     * @return the value of high_voltage_hitch_event.id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_hitch_event.id
     *
     * @param id the value for high_voltage_hitch_event.id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_hitch_event.switch_id
     *
     * @return the value of high_voltage_hitch_event.switch_id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_hitch_event.switch_id
     *
     * @param switchId the value for high_voltage_hitch_event.switch_id
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_hitch_event.hitch_reason
     *
     * @return the value of high_voltage_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public Integer getHitchReason() {
        return hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_hitch_event.hitch_reason
     *
     * @param hitchReason the value for high_voltage_hitch_event.hitch_reason
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public void setHitchReason(Integer hitchReason) {
        this.hitchReason = hitchReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_hitch_event.hitch_phase
     *
     * @return the value of high_voltage_hitch_event.hitch_phase
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public String getHitchPhase() {
        return hitchPhase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_hitch_event.hitch_phase
     *
     * @param hitchPhase the value for high_voltage_hitch_event.hitch_phase
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public void setHitchPhase(String hitchPhase) {
        this.hitchPhase = hitchPhase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_voltage_hitch_event.hitch_time
     *
     * @return the value of high_voltage_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public Date getHitchTime() {
        return hitchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_voltage_hitch_event.hitch_time
     *
     * @param hitchTime the value for high_voltage_hitch_event.hitch_time
     *
     * @mbggenerated Sat Jan 16 06:33:53 CST 2016
     */
    public void setHitchTime(Date hitchTime) {
        this.hitchTime = hitchTime;
    }
}