package com.gdut.dongjun.domain.po;

import java.util.Date;

public class HistoryHighVoltageCurrent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_high_voltage_current.id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_high_voltage_current.time
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_high_voltage_current.phase
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_high_voltage_current.value
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_high_voltage_current.switch_id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    private String switchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_high_voltage_current.id
     *
     * @return the value of history_high_voltage_current.id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_high_voltage_current.id
     *
     * @param id the value for history_high_voltage_current.id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_high_voltage_current.time
     *
     * @return the value of history_high_voltage_current.time
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_high_voltage_current.time
     *
     * @param time the value for history_high_voltage_current.time
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_high_voltage_current.phase
     *
     * @return the value of history_high_voltage_current.phase
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_high_voltage_current.phase
     *
     * @param phase the value for history_high_voltage_current.phase
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_high_voltage_current.value
     *
     * @return the value of history_high_voltage_current.value
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_high_voltage_current.value
     *
     * @param value the value for history_high_voltage_current.value
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_high_voltage_current.switch_id
     *
     * @return the value of history_high_voltage_current.switch_id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_high_voltage_current.switch_id
     *
     * @param switchId the value for history_high_voltage_current.switch_id
     *
     * @mbggenerated Thu Apr 21 17:22:43 CST 2016
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }
}