package com.gdut.dongjun.domain.po;

public class Line {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.name
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.substation_id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    private String substationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.id
     *
     * @return the value of line.id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.id
     *
     * @param id the value for line.id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.name
     *
     * @return the value of line.name
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.name
     *
     * @param name the value for line.name
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.substation_id
     *
     * @return the value of line.substation_id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public String getSubstationId() {
        return substationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.substation_id
     *
     * @param substationId the value for line.substation_id
     *
     * @mbggenerated Mon Nov 23 02:45:55 CST 2015
     */
    public void setSubstationId(String substationId) {
        this.substationId = substationId;
    }
}