package com.gdut.dongjun.domain.po;

public class LocationSwitch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_switch.id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_switch.user_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_switch.switch_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    private String switchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_switch.type
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_switch.id
     *
     * @return the value of location_switch.id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_switch.id
     *
     * @param id the value for location_switch.id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_switch.user_id
     *
     * @return the value of location_switch.user_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_switch.user_id
     *
     * @param userId the value for location_switch.user_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_switch.switch_id
     *
     * @return the value of location_switch.switch_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_switch.switch_id
     *
     * @param switchId the value for location_switch.switch_id
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_switch.type
     *
     * @return the value of location_switch.type
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_switch.type
     *
     * @param type the value for location_switch.type
     *
     * @mbggenerated Sat Feb 27 12:25:36 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}