package com.gdut.dongjun.domain.po;

public class SwitchOperation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_operation.description
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_operation.id
     *
     * @return the value of switch_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_operation.id
     *
     * @param id the value for switch_operation.id
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_operation.description
     *
     * @return the value of switch_operation.description
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_operation.description
     *
     * @param description the value for switch_operation.description
     *
     * @mbggenerated Fri Apr 15 12:10:49 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}