package com.gdut.dongjun.domain.po;

public class Switch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.name
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.address
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.sim_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.device_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.protocal
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private Integer protocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.longitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.latitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch.line_id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    private String lineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.id
     *
     * @return the value of switch.id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.id
     *
     * @param id the value for switch.id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.name
     *
     * @return the value of switch.name
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.name
     *
     * @param name the value for switch.name
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.address
     *
     * @return the value of switch.address
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.address
     *
     * @param address the value for switch.address
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.sim_number
     *
     * @return the value of switch.sim_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.sim_number
     *
     * @param simNumber the value for switch.sim_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.device_number
     *
     * @return the value of switch.device_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.device_number
     *
     * @param deviceNumber the value for switch.device_number
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.protocal
     *
     * @return the value of switch.protocal
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public Integer getProtocal() {
        return protocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.protocal
     *
     * @param protocal the value for switch.protocal
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setProtocal(Integer protocal) {
        this.protocal = protocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.longitude
     *
     * @return the value of switch.longitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.longitude
     *
     * @param longitude the value for switch.longitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.latitude
     *
     * @return the value of switch.latitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.latitude
     *
     * @param latitude the value for switch.latitude
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch.line_id
     *
     * @return the value of switch.line_id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch.line_id
     *
     * @param lineId the value for switch.line_id
     *
     * @mbggenerated Wed Aug 12 11:48:42 CST 2015
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

}