package com.gdut.dongjun.domain.po;

import java.util.Date;

public class Voltage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voltage.id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voltage.time
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voltage.phase
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voltage.value
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voltage.switch_id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    private String switchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voltage.id
     *
     * @return the value of voltage.id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voltage.id
     *
     * @param id the value for voltage.id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voltage.time
     *
     * @return the value of voltage.time
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voltage.time
     *
     * @param time the value for voltage.time
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voltage.phase
     *
     * @return the value of voltage.phase
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voltage.phase
     *
     * @param phase the value for voltage.phase
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voltage.value
     *
     * @return the value of voltage.value
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voltage.value
     *
     * @param value the value for voltage.value
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voltage.switch_id
     *
     * @return the value of voltage.switch_id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voltage.switch_id
     *
     * @param switchId the value for voltage.switch_id
     *
     * @mbggenerated Sat Aug 08 14:28:09 CST 2015
     */
    public void setSwitchId(String switchId) {
        this.switchId = switchId;
    }
}