package com.gdut.dongjun.domain.po.authc;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.text
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.imgUrl
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.iconCls
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String iconcls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.className
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.leaf
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private Integer leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.sort
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_id
     *
     * @return the value of module.parent_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_id
     *
     * @param parentId the value for module.parent_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.text
     *
     * @return the value of module.text
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.text
     *
     * @param text the value for module.text
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.imgUrl
     *
     * @return the value of module.imgUrl
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.imgUrl
     *
     * @param imgurl the value for module.imgUrl
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.iconCls
     *
     * @return the value of module.iconCls
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.iconCls
     *
     * @param iconcls the value for module.iconCls
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.className
     *
     * @return the value of module.className
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.className
     *
     * @param classname the value for module.className
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.leaf
     *
     * @return the value of module.leaf
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public Integer getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.leaf
     *
     * @param leaf the value for module.leaf
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setLeaf(Integer leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.sort
     *
     * @return the value of module.sort
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.sort
     *
     * @param sort the value for module.sort
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}