package com.gdut.dongjun.domain.po.authc;

public class RoleModulePermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_permission.role_module_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String roleModuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module_permission.permission_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    private String permissionId;

    public RoleModulePermissionKey() {
		super();
	}

	public RoleModulePermissionKey(String id, String p) {
    	
    	this.permissionId = p;
    	this.roleModuleId  = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_permission.role_module_id
     *
     * @return the value of role_module_permission.role_module_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getRoleModuleId() {
        return roleModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_permission.role_module_id
     *
     * @param roleModuleId the value for role_module_permission.role_module_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setRoleModuleId(String roleModuleId) {
        this.roleModuleId = roleModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module_permission.permission_id
     *
     * @return the value of role_module_permission.permission_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module_permission.permission_id
     *
     * @param permissionId the value for role_module_permission.permission_id
     *
     * @mbggenerated Sat Nov 14 14:40:29 CST 2015
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }
}