package com.gdut.dongjun.dto;

public class LowVoltageSwitch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.id
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.name
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.address
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.sim_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String simNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.device_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.longitude
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.latitude
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.inline_index
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String inlineIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column low_voltage_switch.line_id
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    private String lineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column low_voltage_switch.id
     *
     * @return the value of low_voltage_switch.id
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column low_voltage_switch.id
     *
     * @param id the value for low_voltage_switch.id
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column low_voltage_switch.name
     *
     * @return the value of low_voltage_switch.name
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column low_voltage_switch.name
     *
     * @param name the value for low_voltage_switch.name
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column low_voltage_switch.address
     *
     * @return the value of low_voltage_switch.address
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column low_voltage_switch.address
     *
     * @param address the value for low_voltage_switch.address
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column low_voltage_switch.sim_number
     *
     * @return the value of low_voltage_switch.sim_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public String getSimNumber() {
        return simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column low_voltage_switch.sim_number
     *
     * @param simNumber the value for low_voltage_switch.sim_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public void setSimNumber(String simNumber) {
        this.simNumber = simNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column low_voltage_switch.device_number
     *
     * @return the value of low_voltage_switch.device_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column low_voltage_switch.device_number
     *
     * @param deviceNumber the value for low_voltage_switch.device_number
     *
     * @mbggenerated Tue Jan 19 15:22:49 CST 2016
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getInlineIndex() {
		return inlineIndex;
	}

	public void setInlineIndex(String inlineIndex) {
		this.inlineIndex = inlineIndex;
	}

	public String getLineId() {
		return lineId;
	}

	public void setLineId(String lineId) {
		this.lineId = lineId;
	}

}