package com.gdut.dongjun.domain.vo;

import java.util.ArrayList;
import java.util.List;

import com.gdut.dongjun.domain.po.HighVoltageHitchEvent;
import com.gdut.dongjun.domain.po.HighVoltageSwitch;

public class HighVoltageHitchEventVo {

	private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.switch_id
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String switchName;
    
    private String switchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.change_type
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private Integer changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_reason
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String hitchReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_phase
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String hitchPhase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.hitch_time
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String hitchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.solve_people
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String solvePeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.solve_time
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String solveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_voltage_hitch_event.solve_way
     *
     * @mbggenerated Thu Mar 24 15:48:59 CST 2016
     */
    private String solveWay;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSwitchName() {
		return switchName;
	}

	public void setSwitchName(String switchName) {
		this.switchName = switchName;
	}

	public String getSwitchAddress() {
		return switchAddress;
	}

	public void setSwitchAddress(String switchAddress) {
		this.switchAddress = switchAddress;
	}

	public Integer getChangeType() {
		return changeType;
	}

	public void setChangeType(Integer changeType) {
		this.changeType = changeType;
	}

	public String getHitchReason() {
		return hitchReason;
	}

	public void setHitchReason(String hitchReason) {
		this.hitchReason = hitchReason;
	}

	public String getHitchPhase() {
		return hitchPhase;
	}

	public void setHitchPhase(String hitchPhase) {
		this.hitchPhase = hitchPhase;
	}

	public String getHitchTime() {
		return hitchTime;
	}

	public void setHitchTime(String hitchTime) {
		this.hitchTime = hitchTime;
	}

	public String getSolvePeople() {
		return solvePeople;
	}

	public void setSolvePeople(String solvePeople) {
		this.solvePeople = solvePeople;
	}

	public String getSolveTime() {
		return solveTime;
	}

	public void setSolveTime(String solveTime) {
		this.solveTime = solveTime;
	}

	public String getSolveWay() {
		return solveWay;
	}

	public void setSolveWay(String solveWay) {
		this.solveWay = solveWay;
	}
    
    public HighVoltageHitchEventVo() {
    	super();
    }
    
    
    
    public HighVoltageHitchEventVo(String id, String switchName,
			String switchAddress, Integer changeType, String hitchReason,
			String hitchPhase, String hitchTime, String solvePeople,
			String solveTime, String solveWay) {
		super();
		this.id = id;
		this.switchName = switchName;
		this.switchAddress = switchAddress;
		this.changeType = changeType;
		this.hitchReason = hitchReason;
		this.hitchPhase = hitchPhase;
		this.hitchTime = hitchTime;
		this.solvePeople = solvePeople;
		this.solveTime = solveTime;
		this.solveWay = solveWay;
	}

	public HighVoltageHitchEventVo(HighVoltageHitchEvent event) {
    	this(event.getId(), null, null, event.getChangeType(), event.getHitchReason(),
    		event.getHitchPhase(), event.getHitchTime(), event.getSolvePeople(),
    		event.getSolveTime(), event.getSolveWay());
    }
	
	private static void addSwitchMessage(HighVoltageHitchEventVo eventVo, HighVoltageSwitch s) {
		eventVo.setSwitchName(s.getName());
		eventVo.setSwitchAddress(s.getAddress());
	}
    
    public static List<HighVoltageHitchEventVo> createHitchEventVoList(
    		List<HighVoltageHitchEvent> events, List<HighVoltageSwitch> switchs) {
    	List<HighVoltageHitchEventVo> list = new ArrayList<>(events.size());
    	for(HighVoltageHitchEvent event : events) {
    		HighVoltageHitchEventVo eventVo = new HighVoltageHitchEventVo(event);
    		for(HighVoltageSwitch s : switchs) {
    			if(s.getId().equals(event.getSwitchId())) {
    				addSwitchMessage(eventVo, s);
    			}
    		}
    		list.add(eventVo);
    	}
    	return list;
    }
}
